### ISSUE TITLE
Integrate with neovim-treesitter

### ISSUE THREAD

**Issue by jonatanklosko** [elixir-lang/tree-sitter-elixir#1]
The goal is to update the Elixir integration points in [`nvim-treesitter`](https://github.com/nvim-treesitter/nvim-treesitter) to use this repository.

cc @connorlay, @nifoc

**Comment by nifoc** [comment]
Quick update from my end:

I had way less time than I initially thought over the weekend, but I did find some time to start updating the queries.
I did not run into any issues and will try to finish things up during the evenings.

**Comment by connorlay** [comment]
> Quick update from my end:
> 
> I had way less time than I initially thought over the weekend, but I did find some time to start updating the queries. I did not run into any issues and will try to finish things up during the evenings.

Hi @nifoc , it sounds like we may be working on the same thing. Are you interested in collaborating with me on the integration with Neovim? I'm on a break from work this week and have a good amount of time set aside for open source work.

**Comment by nifoc** [comment]
Hi @connorlay,
if you have already started working on updating the queries, please feel free to just submit a PR! 😄 It sounds like you have way more time for it this week and I'm really eager to see the update land.

Btw. I have to say that the changes you made to the queries a while back really makes updating them easier! :) The ones I wrote initially were way too complex.

**Comment by connorlay** [comment]
Draft PR is up with highlights and injections completed: https://github.com/nvim-treesitter/nvim-treesitter/pull/1904

**Comment by jonatanklosko** [comment]
Amazing!!

**Comment by nifoc** [comment]
This is awesome! Thank you so much for your work 🥳

**Comment by connorlay** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/1904 is merged now and is available now for users of neovim nightly. Users of neovim stable will have to wait for the 0.5-compat release, or upgrade manually to nightly.

During review I captured the following tasks we'll want to get after soon:
* Open a PR against neovim to expose the tree sitter cursor query match limit via user configuration. This is required for `locals.scm` to function with deep pattern matches. See https://github.com/neovim/neovim/pull/14915
* Open a PR against [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects) (and any other community plugin that supports Elixir) to update the queries to work with the new parser grammar.

**Comment by connorlay** [comment]
Quick update: I'm working on a draft PR migrating [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/130) to the new parser.
