### ISSUE TITLE
TS is slow when parsing elixir files.

### ISSUE THREAD

**Issue by qwexvf** [elixir-lang/tree-sitter-elixir#13]
When i open a elixir file i get `TS took 356ms to parse document, will be disabled for current file.`
It happens with small or larger file.

is this because i'm on a m1 mac?

**Comment by jonatanklosko** [comment]
@connorlay Thanks for confirming! I know you already optimised the queries for performance, so not sure how much more we can do. If you have any ideas feel free to open an issue on nvim-treesitter.
