### ISSUE TITLE
.exs files not getting syntax highlighting

### ISSUE THREAD

**Issue by mirtyl-wacdec** [elixir-lang/tree-sitter-elixir#19]
`.ex` files work great but `.exs` files are getting no highlighting at all.

**Comment by jonatanklosko** [comment]
Hey @mirtyl-wacdec, could you elaborate on your use case? Do you mean highlighting in some particular editor?

**Comment by mirtyl-wacdec** [comment]
Yes, sorry. I was using neovim 0.6.0. using the https://github.com/nvim-treesitter/nvim-treesitter plugin. I arrived at this repo through there.

**Comment by josevalim** [comment]
No problem! You should report this in the nvim/plugin. :) There is not much we can do from here.
