### ISSUE TITLE
Remote function calls wrongly pointing to local function

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/tree-sitter-elixir#26]
Navigating GitHub today I discovered that in [this case](https://github.com/teamon/tesla/blob/008b287da51620852c7564f369a90eecf92f5542/lib/tesla.ex#L535) the remote function call does not properly point to the proper module, it points to a local function defined inside the module.

![Screen Shot 2022-02-14 at 17 39 27](https://user-images.githubusercontent.com/651203/153907341-d861baf7-698c-431c-9cec-2eb87ca47922.png)

**Comment by the-mikedavis** [comment]
This is a limitation of "search-based" code-navigation on GitHub: all definitions/references for functions/modules of the same name are given, even in cases like this where two functions have the same name but are actually separate. See the [search vs. precise docs](https://docs.github.com/en/repositories/working-with-files/using-files/navigating-code-on-github#precise-and-search-based-navigation) from GitHub.

We'll need to implement stack-graphs queries to solve this (and other scenarios like references to aliased modules). Stack-graphs are quite new, though - they're only implemented for python so far. Afaik, GitHub is currently in the process of open-sourcing and improving documentation on it.

**Comment by josevalim** [comment]
Yes, that’s working as intended by the current version of search based navigation. Precise navigation will solve that but not currently available.

Also Keep in mind the code navigation does not work across projects either (so it only finds definitions within a project).
