### ISSUE TITLE
Publishing to crates.io

### ISSUE THREAD

**Issue by the-mikedavis** [elixir-lang/tree-sitter-elixir#35]
GitHub and some other tree-sitter consumers (the Lapce editor comes to mind) consume tree-sitter parsers through Rust crates.

@patrickt would be happy to set up the crate but would like to add us as maintainers of the package. What do you think @jonatanklosko? (And I imagine you would like to be a crate maintainer as well? And maybe @josevalim?)

**Comment by jonatanklosko** [comment]
Sounds good, please go ahead! I've just signed into crates, so feel free to add :)

**Comment by J3RN** [comment]
Along these same lines it would be nice to publish the generate JavaScript package to NPM for easy consumption by JS projects.

**Comment by jonatanklosko** [comment]
Published v0.1.0.
