### ISSUE TITLE
Predicate syntax reference

### ISSUE THREAD

**Issue by andrhua** [elixir-lang/tree-sitter-elixir#39]
There's perhaps a small typo in [injections queries](https://github.com/elixir-lang/tree-sitter-elixir/blob/main/queries/injections.scm#L5), where `#eq` should've been `#eq?`, at least that's what Lua TS binding lib uses, as well as Rust and Webassembly. Here's an error from nvim:
```
Error detected while processing FileType Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:418: No handler for eq
stack traceback:
        [C]: in function 'error'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:418: in function 'match_preds'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:564: in function '(for generator)'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:314: in function '_get_injections'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:131: in function 'parse'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:68: in function '_create_parser'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:94: in function 'get_parser'
```
But I'm not sure since [docs](https://tree-sitter.github.io/tree-sitter/using-parsers#query-syntax) (*Predicates* section) state that predicates are handled by "higher level code", so perhaps the author of this query had used parser where question mark is omitted from predicate syntax. Anyway, adding `?` fixed mentioned error for me.

Minimal reproducing code:
```elixir
defmodule Foo do
  @foo ~w(bar) # error happens here
end
```

**Comment by the-mikedavis** [comment]
Good catch! That line should be `#eq?`. All tree-sitter consumers that I know of use `#eq?`, but you're right that they're implemented by higher level code. For example, neovim implements `#any-of?` while tree-sitter-cli does not.

I'll push a commit to fix this. Thanks for the report!

**Comment by jonatanklosko** [comment]
Good catch, currently I get this:

![image](https://user-images.githubusercontent.com/17034772/182924580-a0080998-6dc2-487b-9b8d-dc6ed9fccc0d.png)

and it's the same when changing `#eq` to `#whatever`, so it seems like there's some error that is being silently ignored. With the change it works as expected

![image](https://user-images.githubusercontent.com/17034772/182925086-a02129da-e661-4de2-862c-95837d719a6d.png)
