### ISSUE TITLE
Emacs tree-sitter support 

### ISSUE THREAD

**Issue by wingyplus** [elixir-lang/tree-sitter-elixir#4]
It would be interesting if we have support for Emacs. Currently, I'm setting Emacs and tree-sitter using https://github.com/emacs-tree-sitter/elisp-tree-sitter to work on my local machine. I can help try integrating on it. :)

**Comment by jonatanklosko** [comment]
Sounds good, feel free to create an integration :D Is there anything necessary on this end to support it?

**Comment by jonatanklosko** [comment]
Cool! For some existing queries see [highlights.scm](https://github.com/elixir-lang/tree-sitter-elixir/blob/main/queries/highlights.scm) in this repo and also https://github.com/nvim-treesitter/nvim-treesitter/pull/1904. You probably can reuse most of that and just change the `@annotations` to whatever is expected :)

**Comment by wingyplus** [comment]
Sorry for not responding for a long time. I've trying with `highlight.scm` from `nvim-tree-sitter`. I tried it with `lib/elixir/lib/code/formatter.ex` in `elixir` repository and the result looks like:

Before:

<img width="929" alt="Screen Shot 2564-11-13 at 23 50 34" src="https://user-images.githubusercontent.com/484530/141652167-7f742006-85cc-4735-a685-52259f5e18b5.png">
<img width="773" alt="Screen Shot 2564-11-13 at 23 50 51" src="https://user-images.githubusercontent.com/484530/141652176-85278aad-4d7f-48e0-87d9-580f42ff1455.png">
<img width="817" alt="Screen Shot 2564-11-13 at 23 51 05" src="https://user-images.githubusercontent.com/484530/141652178-bc2a5ac2-9951-46a0-a2ea-941b4141e168.png">

After:

<img width="930" alt="Screen Shot 2564-11-13 at 23 51 26" src="https://user-images.githubusercontent.com/484530/141652188-649897c9-fc9c-482d-808d-963ceb0845f3.png">
<img width="762" alt="Screen Shot 2564-11-13 at 23 51 38" src="https://user-images.githubusercontent.com/484530/141652200-92059c43-fbb3-4e65-adf7-c889549a1e21.png">
<img width="835" alt="Screen Shot 2564-11-13 at 23 52 17" src="https://user-images.githubusercontent.com/484530/141652202-5f9daf93-71a7-433b-8207-c238240befdc.png">

I found an issue that some atoms in `required_parens_on_binary_operands` got highlighted and some not, I'm not sure why. But overall looks good.

**Comment by jonatanklosko** [comment]
Hmm, the module attributes look off, and some of the keywords like `def`, `case` are not highlighted properly. You can play around with queries order, I think the built-in highlighter always uses whatever matches first (ordering from most to least specific queries), while nbim-tree-sitter works the other way round (subsequent highlightings take precedence).

FTR here's what I get using the built-in highlighter with [these](https://github.com/elixir-lang/tree-sitter-elixir/blob/main/queries/highlights.scm) queries.

![image](https://user-images.githubusercontent.com/17034772/141653541-303934ce-94e0-489b-817e-bcbe02e38ad3.png)
![image](https://user-images.githubusercontent.com/17034772/141653542-72c91eb9-b38b-4a28-99e3-e5e0d44a90f6.png)

**Comment by wingyplus** [comment]
Thanks for your advice. The syntax highlighter is pretty straightforward than I thought. 

<img width="815" alt="Screen Shot 2564-11-14 at 14 58 37" src="https://user-images.githubusercontent.com/484530/141672779-e35bbf85-4dd1-48b2-bdf2-fc6ba92befb9.png">
<img width="768" alt="Screen Shot 2564-11-14 at 14 58 11" src="https://user-images.githubusercontent.com/484530/141672784-2df458e1-15df-481b-bee4-1586d4444a8b.png">
<img width="914" alt="Screen Shot 2564-11-14 at 14 57 51" src="https://user-images.githubusercontent.com/484530/141672786-f6cca194-e73d-4449-a358-81ecf234fe04.png">

**Comment by wingyplus** [comment]
I opened a branch on my fork [here](https://github.com/wingyplus/tree-sitter-langs/tree/elixir-tree-sitter). I need help testing before sending a patch to upstream. :)

**Comment by wingyplus** [comment]
Update the progress. I sent a PR to the tree-sitter-langs package to register a highlight query [here](https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/57).

**Comment by wkirschbaum** [comment]
I am playing with the feature/tree-sitter branch and have some version working with font-locking, indentation and navigation. I don't know tree-sitter very well and have not worked a lot on major modes, so not sure if what I am doing is correct. Maybe we can merge some version of this into the elixir-mode repository for when emacs 29 is out?

It is ready enough for me to use it during the week and tweak an iron out: https://github.com/wkirschbaum/elixir-mode/blob/main/elixir-mode.el

**Comment by wingyplus** [comment]
Not sure if this is what you’re looking for for the moduledoc issue https://github.com/wingyplus/tree-sitter-langs/blob/elixir-queries/queries/elixir/highlights.scm

**Comment by wkirschbaum** [comment]
@wingyplus i see the arrows are misleading. i meant those as an advantage, not an issue. I used the highlights file to generate the treesit-settings function, it is almost the same except for some tweaks. 

There is a moduledoc issue, but seems to be either emacs treesit bug ( i see there are some fixes still rolling in ) or a elixir treesitter bug. I will investigate a bit this week.

**Comment by wingyplus** [comment]
Ah I see. If we can modify string after doc attributes (moduledoc, doc, typedoc) into a comment that’s would be great.

**Comment by ryanwinchester** [comment]
This is an issue that I see almost everywhere that I see tree-sitter-elixir being used. It happens in [Zed](https://zed.dev) and [Nova](https://nova.app).

It makes other editors I want to try unusable except for VSCode because it drives me nuts (I write _a lot_ of docs in my code).

e.g. https://github.com/zed-industries/community/issues/814

I wish I knew what GitHub was doing to fix it on their end, since they apparently also use tree-sitter-elixir.

**Comment by BlindingDark** [comment]
Hi @ryanwinchester, I think wkirschbaum/elixir-ts-mode has already marked it as comment style. :sunglasses: 

https://github.com/wkirschbaum/elixir-ts-mode/blob/main/elixir-ts-mode.el#L70

**Comment by ryanwinchester** [comment]
Is this not something that `tree-sitter-elixir` could fix, or does every editor that uses it have to set that up on their own?

**Comment by BlindingDark** [comment]
In fact, the highlight provided by `tree-sitter-elixir` also marks it as comment style.

https://github.com/elixir-lang/tree-sitter-elixir/blob/main/queries/highlights.scm#L8

So maybe those editors don't set the correct colors for the `comment.doc` style.

**Comment by ryanwinchester** [comment]
Weird. It doesn't look correct in here either: https://elixir-lang.org/tree-sitter-elixir

**Comment by BlindingDark** [comment]
Because it uses a simple version of the highlighting rules.
You can copy the complete highlighting rules I mentioned above into the lower left corner of the demo web page.

**Comment by ryanwinchester** [comment]
> Because it uses a simple version of the highlighting rules. You can copy the complete highlighting rules I mentioned above into the lower left corner of the demo web page.

Yes I did, and it is still not correct for me. Does it work for you?

**Comment by jonatanklosko** [comment]
@ryanwinchester tree-sitter-elixir handles the parsing part, that is turning code into meaningful nodes. The rules for highlighting nodes are generally up to the user (or in this case the editor projects). In this repo we have `queries/highlights.scm`, which is what GitHub uses and we explicitly mark docstrings as comments:

https://github.com/elixir-lang/tree-sitter-elixir/blob/b20eaa75565243c50be5e35e253d8beb58f45d56/queries/highlights.scm#L7-L21

> Weird. It doesn't look correct in here either: https://elixir-lang.org/tree-sitter-elixir

The demo page isn't meant for highlighting, it's a playground where you can see how the code gets parsed and then match queries against the parse tree. The colors are only to distinguish the query results.

**Comment by ryanwinchester** [comment]
> In this repo we have `queries/highlights.scm`, which is what GitHub uses and we explicitly mark docstrings as comments

Thanks, so it's easy-mode for editors if they use that? Thanks :)

**Comment by BlindingDark** [comment]
@ryanwinchester 
![image](https://user-images.githubusercontent.com/13600799/219875472-18744cba-6d83-4efc-a988-4e1bf7d6a96a.png)

**Comment by jonatanklosko** [comment]
> Thanks, so it's easy-mode for editors if they use that?

Yeah, when integrating with the given editor you'd use pretty much the same query and just make sure to use node names that the editor understands for highliting (e.g. `@comment`).

[Here](https://github.com/nvim-treesitter/nvim-treesitter/blob/17d7cf6f4b4057a949e86df6fbc2e271ba788823/queries/elixir/highlights.scm#L212-L227) is an example in Nvim :)

**Comment by wkirschbaum** [comment]
this is what it currently looks like in elixir-ts-mode
![image](https://user-images.githubusercontent.com/1431483/219879554-c2978846-f3b5-4d2c-ac99-772090ebc5e1.png)

Should comment use the same font  as doc comments?

**Comment by wkirschbaum** [comment]
i don't know about other editors, but in emacs it is really easy to modify the faces. giving fever options is not better.

**Comment by ryanwinchester** [comment]
Maybe we're getting into subjective territory but as long as it's comment-like and not rendered like a normal module attribute + string, it's good.

Personally I prefer it to just be the same as comments. Like how GitHub and VSCode handle it.

```elixir
@doc "foobar"

@moduledoc """
foobar
"""

# comment

"string"

~S"""
foobar
"""
```

**Comment by wkirschbaum** [comment]
@ryanwinchester nothing stops you in emacs and currently elixir-ts-mode to set them to the same face. if we tag moduledocs with comment then the user won't be able to easilty specify them as two different faces if they want to. I don't think it is subjective, as it is now you have more options to customize your fontification and don't think we should remove that option.

**Comment by ryanwinchester** [comment]
> @ryanwinchester nothing stops you in emacs and currently elixir-ts-mode to set them to the same face. if we tag moduledocs with comment then the user won't be able to easilty specify them as two different faces if they want to. I don't think it is subjective, as it is now you have more options to customize your fontification and don't think we should remove that option.

No, I agree.

**Comment by wkirschbaum** [comment]
@wingyplus is there any reason for this to still be open? Is there anything which needs to be done? In the next month or two I will try to get elixir-ts-mode into emacs core and currently we have elixir-ts-mode and heex-ts-mode on MELPA for the next year or so.

**Comment by wingyplus** [comment]
@wkirschbaum Thank you for creating those ts-modes. I'm very impressed. 

So I'll close it now. 🙇
