### ISSUE TITLE
Symbols highighting is broken

### ISSUE THREAD

**Issue by freevova** [elixir-lang/tree-sitter-elixir#43]
Symbols highlighting doesn't work for me:
```elixir
defmodule Test do
  def call do
    %{name: "name", age: 20}
    [name: "name", age: 20]
  end
end
```

![зображення](https://user-images.githubusercontent.com/15907211/196647613-13de5649-7bef-455e-a3d2-3c1eb6717416.png)

I use **[morhetz/gruvbox](https://github.com/morhetz/gruvbox)** plugin for my color scheme, but symbol highlighting doesn't work with other color schemes as well.

Packer instruction is:
```lua
use {"nvim-treesitter/nvim-treesitter", config = require "plugins.treesitter", run = ":TSUpdate"}
```
and my configs are:
```lua
return function()
  local ts_config = require("nvim-treesitter.configs")

  ts_config.setup {
    ensure_installed = {
      "bash",
      "css",
      "elixir",
      "erlang",
      "haskell",
      "graphql",
      "javascript",
      "json",
      "lua",
      "html",
      "yaml"
    },
    highlight = {
      enable = true,
      use_languagetree = true
    },
    indent = {
      enable = true
    }
  }

  vim.opt.foldmethod = 'expr'
  vim.opt.foldexpr   = 'nvim_treesitter#foldexpr()'

  vim.cmd([[ autocmd BufReadPost,FileReadPost * normal zR ]])
end
```
Previously symbol highlighting worked correctly and only after updating pluginі something went wrong. Can someone help with this, please?

**Comment by jonatanklosko** [comment]
Hey @freevova! This seems more related to `nvim-treesitter`. @connorlay any ideas? :)

**Comment by ryanwinchester** [comment]
Probably related to https://github.com/nvim-treesitter/nvim-treesitter/pull/1904

**Comment by josevalim** [comment]
Closing this for now, as it is not tree-sitter-elixir related per se. Glad to reopen otherwise.
