### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by 0-wiz-0** [elixir-lang/tree-sitter-elixir#48]
For packaging, it's good to have stable release tarballs to use. I'd like to package this for pkgsrc, but AFAICT there is not even a tag yet.
Please make a release or at least tag a version. Thank you.

**Comment by jonatanklosko** [comment]
Hey @0-wiz-0, see https://github.com/elixir-lang/tree-sitter-elixir/issues/44#issuecomment-1301925843, we keep a release on hold because it's unclear how versions should be numbered. FWIW most package managers (npm/crate) allow pointing to a specific SHA version on GitHub.

**Comment by 0-wiz-0** [comment]
Thanks, I commented on that one.
I used the SHA version for now, but I still believe that official releases are better :)
