### ISSUE TITLE
Inject Markdown in heredocs?

### ISSUE THREAD

**Issue by georgeguimaraes** [elixir-lang/tree-sitter-elixir#61]
Would it be possible to inject markdown for heredocs? 

This would make highlighting, snippets, and supposedly linters for Markdown on Neovim work inside .ex files.

Does it even make sense?

**Comment by josevalim** [comment]
Yes, but I believe those injections typically are done inside the editors themselves. :) So you would need to check with the Neovim folks. :)

**Comment by the-mikedavis** [comment]
We do this in Helix for example: https://github.com/helix-editor/helix/blob/68c7537de522cf6b38705a7af51eeaac260fdc98/runtime/queries/elixir/injections.scm#L13-L21

<img width="631" alt="Screenshot 2023-10-24 at 09 20 01" src="https://github.com/elixir-lang/tree-sitter-elixir/assets/21230295/e32498fa-910f-49cf-8dbe-72ee0c52d228">

It looks like nvim-treesitter already has this injection too so I assume it should work but I haven't tried it: https://github.com/nvim-treesitter/nvim-treesitter/blob/4199be485cd85662d8ff1dc8c4cc78d819fad6cd/queries/elixir/injections.scm#L5-L14

**Comment by georgeguimaraes** [comment]
Nice, I thought it was supposed to go here https://github.com/elixir-lang/tree-sitter-elixir/blob/main/queries/injections.scm
