### ISSUE TITLE
Advice on tests for matching and replacing code for `ast-grep`?

### ISSUE THREAD

**Issue by dimitarvp** [elixir-lang/tree-sitter-elixir#63]
Hello,
Recently I've opened a PR in `ast-grep`: https://github.com/ast-grep/ast-grep/pull/749, that adds Elixir support to the tool so you can search and replace code from the command line. I've confirmed that it works for the several cases that I had in mind.

I can't open a discussion in this repo so I am opening an issue asking for advice on what kinds of matching and replacing would be good relevant tests for this tool? (It uses `tree-sitter` and `tree-sitter-elixir`.)

Example of a replace test I just added there is below. I am not asking you to be an expert in `ast-grep`'s syntax, I am merely asking if you can give me ideas on less bare and more believable match / replace tests. I'll translate those to `ast-grep` rules.

Link to the Rust file exercising the Elixir tests: https://github.com/ast-grep/ast-grep/pull/749/files#diff-0ea893cc4bb08a539d62faa2f16dc54b322a191b18a5462f875f8731c47c6259

Input code:
```elixir
Stream.map([1, 2, 3], fn x -> x * 2 end)
```

Search pattern:
```elixir
Stream.map($$$ARGS)
```

Replacer:
```elixir
Enum.map($$$ARGS)
```

Expected output:
```elixir
Enum.map([1, 2, 3], fn x -> x * 2 end)
```

**Comment by jonatanklosko** [comment]
Perhaps `Mod.fun($DATA, fn $ARG -> $MOD.$FUN($ARG) end)` -> `Mod.fun($DATA, &$MOD.$FUN/1)` :)
