### ISSUE TITLE
tree-sitter 0.21.0+ compatibility

### ISSUE THREAD

**Issue by HerringtonDarkholme** [elixir-lang/tree-sitter-elixir#65]
Hi I'm [ast-grep](https://ast-grep.github.io/)'s author. ast-grep is an AST based search tool that supports [elixir](https://github.com/ast-grep/ast-grep/blob/main/crates/language/Cargo.toml#L25).

at the moment tree-sitter-elixir cannot be used with `tree-sitter-0.21.0`. 

More specifically, the cargo manifest disables the usage of newer tree-sitter.

https://github.com/elixir-lang/tree-sitter-elixir/blob/main/Cargo.toml#L23

Appreciate it if you can bump the version dependency!

Reference:
https://github.com/tree-sitter/tree-sitter-go/pull/138/files
https://github.com/tree-sitter/tree-sitter/releases

**Comment by jonatanklosko** [comment]
I updated to `tree-sitter = ">=0.21.0"` and released v0.2.0, let me know if there are any issues :)
