### ISSUE TITLE
Grammar seems to fail when parsing complex patterns

### ISSUE THREAD

**Issue by entilldaniel** [elixir-lang/tree-sitter-elixir#69]
I came across this fairly complex pattern in a sigil when reading the earmark source code:
[`@link_text ~S{(?:\[[^]]*\]|[^][]|\])*}`](https://github.com/pragdave/earmark/blob/df44cab142dfc8325a5fdd1dbc387607920f69b1/lib/earmark_parser/context.ex#L95)

This causes treesitter to parse some of the following brackets and parentheses as unmatched:

![image](https://github.com/elixir-lang/tree-sitter-elixir/assets/2023302/c8c9af77-50f9-48b5-95e9-fee9528b8caa)

**Comment by entilldaniel** [comment]
Oh, sorry. If github is using this grammar then I guess this has to be an issue with my editor.

**Comment by jonatanklosko** [comment]
@entilldaniel yeah, I think has to do with the extension responsible for highlighting brackets, no matter the language :)
