### ISSUE TITLE
Tree-sitter playground is broken

### ISSUE THREAD

**Issue by mwhitworth** [elixir-lang/tree-sitter-elixir#74]
https://elixir-lang.org/tree-sitter-elixir/ appears to be broken, navigating to the URL produces no output by default. `currentFieldName` is an attribute rather than a function now.

It's tricky to try to work out the source of `tree-sitter.js` and how this file varies with the (ever-evolving) tree-sitter API.

<img width="529" alt="Screenshot 2024-10-18 at 12 08 11" src="https://github.com/user-attachments/assets/745efc04-cc1c-414b-93d9-190a51358f0f">

**Comment by jonatanklosko** [comment]
@mwhitworth thanks for the report, fixed :)
